In [1]:
import pandas as pd
import numpy as np

In [2]:
train=pd.read_csv("customer_churn_dataset-training-master.csv")
test=pd.read_csv("customer_churn_dataset-testing-master.csv")

In [3]:
train.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [4]:
test.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0

In [5]:
train.shape

(440833, 12)

In [6]:
test.shape

(64374, 12)

In [7]:
train.columns

Index(['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency',
       'Support Calls', 'Payment Delay', 'Subscription Type',
       'Contract Length', 'Total Spend', 'Last Interaction', 'Churn'],
      dtype='object')

In [8]:
test.columns

Index(['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency',
       'Support Calls', 'Payment Delay', 'Subscription Type',
       'Contract Length', 'Total Spend', 'Last Interaction', 'Churn'],
      dtype='object')

In [9]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  object
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  object
 8   Contract Length    440832 non-null  object
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), object(3)
memory usage: 40.4+ MB

In [10]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64374 entries, 0 to 64373
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         64374 non-null  int64
 1   Age                64374 non-null  int64
 2   Gender             64374 non-null  object
 3   Tenure             64374 non-null  int64
 4   Usage Frequency    64374 non-null  int64
 5   Support Calls      64374 non-null  int64
 6   Payment Delay      64374 non-null  int64
 7   Subscription Type  64374 non-null  object
 8   Contract Length    64374 non-null  object
 9   Total Spend        64374 non-null  int64
 10  Last Interaction   64374 non-null  int64
 11  Churn              64374 non-null  int64
dtypes: int64(9), object(3)
memory usage: 5.9+ MB

In [11]:
train.describe()

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn
count,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000
mean,225398.667955,39.373153,31.256336,15.807494,3.604437,12.965722,631.616223,14.480868,0.567107
std,129531.918550,12.442369,17.255727,8.586242,3.070218,8.258063,240.803001,8.596208,0.495477
min,2.000000,18.000000,1.000000,1.000000,0.000000,0.000000,100.000000,1.000000,0.000000
25%,113621.750000,29.000000,16.000000,9.000000,1.000000,6.000000,480.000000,7.000000,0.000000
50%,226125.500000,39.000000,32.000000,16.000000,3.000000,12.000000,661.000000,14.000000,1.000000
75%,337739.250000,48.000000,46.000000,23.000000,6.000000,19.000000,830.000000,22.000000,1.000000
max,449999.000000,65.000000,60.000000,30.000000,10.000000,30.000000,1000.000000,30.000000,1.000000

In [12]:
train['Contract Length'].value_counts()

Contract Length
Annual       177198
Quarterly    176530
Monthly       87104
Name: count, dtype: int64

In [13]:
train["Subscription Type"].value_counts()

Subscription Type
Standard    149128
Premium     148678
Basic       143026
Name: count, dtype: int64

In [14]:
train['Gender'].value_counts()

Gender
Male      250252
Female    190580
Name: count, dtype: int64

In [15]:
train.dtypes

CustomerID           float64
Age                  float64
Gender                object
Tenure               float64
Usage Frequency      float64
Support Calls        float64
Payment Delay        float64
Subscription Type     object
Contract Length       object
Total Spend          float64
Last Interaction     float64
Churn                float64
dtype: object

In [16]:
## task-3 :Classify each categorical column as:Binary,Nominal
for col in ['Gender', 'Subscription Type', 'Contract Length']:
    print(col, ":", train[col].unique())

Gender : ['Female' 'Male' nan]
Subscription Type : ['Standard' 'Basic' 'Premium' nan]
Contract Length : ['Annual' 'Monthly' 'Quarterly' nan]

In [17]:
cat_cols=['Gender','Subscription Type','Contract Length']
train=train.dropna(subset=cat_cols)

In [18]:
## Task-2 Categorical columns
cat_cols=train.select_dtypes(include=['object']).columns
print("Categorical Columns")
print(list(cat_cols))

Categorical Columns
['Gender', 'Subscription Type', 'Contract Length']

In [19]:
train['Gender'].unique() #->Binary Because it has only male and female

array(['Female', 'Male'], dtype=object)

In [20]:
train['Subscription Type'].unique()

array(['Standard', 'Basic', 'Premium'], dtype=object)

In [21]:
train['Contract Length'].unique()

array(['Annual', 'Monthly', 'Quarterly'], dtype=object)

In [22]:
print("Binary Columns:")
print("Gender")
print("---------------------")
print("Nominal Column:")
print("Subscription Type")
print("Contract Length")
print("-------------------------")

Binary Columns:
Gender
---------------------
Nominal Column:
Subscription Type
Contract Length
-------------------------

In [23]:
## Task 4
## Apply Label Encoding to all binary categorical columns.
from sklearn.preprocessing import LabelEncoder
binary_col=['Gender']
le=LabelEncoder()
train['Gender_le']=le.fit_transform(train['Gender'])

In [24]:
test=test.dropna(subset=cat_cols)

In [25]:
mapping={"Male":1,"Female":0}
test["Gender"]=test["Gender"].map(mapping)

In [26]:
train['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [27]:
## Task 5
## Apply Label Encoding to one nominal categorical column.
le=LabelEncoder()
train['Subscription Type']=le.fit_transform(train['Subscription Type'])

In [28]:
train['Subscription Type'].unique()

array([2, 0, 1])

In [29]:
print(le.classes_)

['Basic' 'Premium' 'Standard']

In [30]:
test['Subscription Type'] = le.transform(test['Subscription Type'])

In [31]:
test['Subscription Type'].unique()

array([0, 2, 1])

In [32]:
## Task 6
## Apply One-Hot Encoding to all nominal categorical columns.
nominal_cols=['Subscription Type','Contract Length']
train=pd.get_dummies(train,columns=nominal_cols,drop_first=True)
test=pd.get_dummies(test,columns=nominal_cols,drop_first=True)

In [33]:
train.columns

Index(['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency',
       'Support Calls', 'Payment Delay', 'Total Spend', 'Last Interaction',
       'Churn', 'Gender_le', 'Subscription Type_1', 'Subscription Type_2',
       'Contract Length_Monthly', 'Contract Length_Quarterly'],
      dtype='object')

In [34]:
train.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn,Gender_le,Subscription Type_1,Subscription Type_2,Contract Length_Monthly,Contract Length_Quarterly
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,932.0,17.0,1.0,0,False,True,False,False
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,557.0,6.0,1.0,0,False,False,True,False
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,185.0,3.0,1.0,0,False,False,False,True
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,396.0,29.0,1.0,1,False,True,True,False
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,617.0,20.0,1.0,1,False,False,True,False

In [35]:
## Task 7
## Apply One-Hot Encoding to one binary column and compare with Label Encoding.
binary_col='Gender'
gender_ohe=pd.get_dummies(train['Gender'],prefix='Gender',drop_first=True)
train = pd.concat([train, gender_ohe], axis=1)

In [36]:
train.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn,Gender_le,Subscription Type_1,Subscription Type_2,Contract Length_Monthly,Contract Length_Quarterly,Gender_Male
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,932.0,17.0,1.0,0,False,True,False,False,False
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,557.0,6.0,1.0,0,False,False,True,False,False
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,185.0,3.0,1.0,0,False,False,False,True,False
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,396.0,29.0,1.0,1,False,True,True,False,True
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,617.0,20.0,1.0,1,False,False,True,False,True

In [38]:
train[['Gender','Gender_le','Gender_Male']].head()

   Gender  Gender_le  Gender_Male
0  Female          0        False
1  Female          0        False
2  Female          0        False
3    Male          1         True
4    Male          1         True